### ISSUE TITLE
slayerCuda missing

### ISSUE THREAD

**Issue by KyungsuKim42** [bamsumit/slayerPytorch#1]
Hello, 

I was trying to install slayerPytorch and run some example, however `python -m unittest`  got failed because there was no module called `slayerCuda`.

Is porting process not complete or am I missing something? 

By the way, thank you for your great work on both theoritical and practical issues on SNN. It helped me a lot.

**Comment by bamsumit** [comment]
Hi, did the installation step go fine? `python3 setup.py install`
It looks like the installation step failed.

**Comment by KyungsuKim42** [comment]
Yes, I've run `python3 setup.py install` and it didn't output any error messages but installation log.

Following is the last part of the error message when I run `python -m unittest`

```
======================================================================
ERROR: test_slayerLoihi001 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayerLoihi001
Traceback (most recent call last):
  File "/home/ssd/kyungsukim/anaconda3/envs/SNN/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/ssd/kyungsukim/anaconda3/envs/SNN/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/kyungsukim/SNN/slayerPytorch/test/test_slayerLoihi001.py", line 9, in <module>
    from slayerLoihi import spikeLayer
  File "/home/kyungsukim/SNN/slayerPytorch/test/../src/slayerLoihi.py", line 11, in <module>
    import slayer
  File "/home/kyungsukim/SNN/slayerPytorch/test/../src/slayer.py", line 8, in <module>
    import slayerCuda
ImportError: /home/ssd/kyungsukim/anaconda3/envs/SNN/lib/python3.6/site-packages/slayerCuda-0.0.0-py3.6-linux-x86_64.egg/slayerCuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration


----------------------------------------------------------------------
Ran 16 tests in 0.014s

FAILED (errors=12)

```

**Comment by bamsumit** [comment]
It looks like liner error. Are you sure you have correct nvidia driver version to go with your cuda version? Table 1 in this link https://docs.nvidia.com/deploy/cuda-compatibility/

**Comment by bamsumit** [comment]
Hi is your issue resolved?

**Comment by KyungsuKim42** [comment]
Sorry for late replying. 
I've checked my driver version is compatible with my CUDA version. (driver version : 396.37, CUDA version : 8.0) 
The same issue(not able to import slayerCuda) occurs when I run `python nmnistMLP.py` at example directory. I'm wondering where can I find the `slayerCuda.py` module because I can't find it in any directory.  
Thank you.

**Comment by bamsumit** [comment]
Hi, 
Are you able to compile and run the NVIDIA CUDA samples included with your cuda installation?

- locate a folder named `NVIDIA_CUDA-8.0_Samples`, copy it to your home directory.
- cd to `1_Utilities/deviceQuery`
- build using `make` and run the exectuable `./deviceQuery`

You will not find the python script for `slayerCuda`. It is automatically generated when you setup.
