### ISSUE TITLE
a question about the output of _spikeFunction of slayer.py

### ISSUE THREAD

**Issue by kkkkkkip** [bamsumit/slayerPytorch#102]
Hello, I have a question about the output of _spikeFunction of slayer.py, which corresponds to the output of pulse neuron. According to my understanding, it should be a binary pulse train, which is a series of 0 or 1, but the output I printed out is not 0 or 1, but the specific value. I don't understand this. I hope to get your reply.

**Comment by bamsumit** [comment]
It should be binary, apart from floating point errors.

**Comment by kkkkkkip** [comment]
My understanding of floating point errors is not very clear. Could you explain it in more detail

**Comment by bamsumit** [comment]
Do you mind sharing the output you get?

**Comment by kkkkkkip** [comment]
_spikeFunction return spikes:
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0.],
[-7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675],
           [ 1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,
             1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426,  1.3426],
           [-7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675,
            -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675, -7.0675],

**Comment by bamsumit** [comment]
can you post the code as well?

**Comment by kkkkkkip** [comment]
def forward(self, spikeInput):
        psp1 = self.slayer1.psp(spikeInput)

        B, C, H, W, T = spikeInput.shape
        psp1_1 = psp1.permute((0, 1, 4, 2, 3))
        psp1_1 = psp1_1.reshape((B, C*T, H, W))
        psp1_1 = torch.nn.functional.interpolate(psp1_1, scale_factor=2, mode='bilinear')
        psp1_1 = psp1_1.reshape(B, C, T, 2*H, 2*W).permute((0, 1, 3, 4, 2))

        spikes_layer_1 = self.slayer1.spike(self.conv1(psp1))
        spikes_layer_2 = self.slayer2.spike(self.conv2(self.slayer2.psp(spikes_layer_1)))
        spikes_layer_3 = self.slayer3.spike(self.upconv1(self.slayer3.psp(spikes_layer_2)) + psp1_1)

        return spikes_layer_3

**Comment by kkkkkkip** [comment]
And I would like to know the specific functions of slayercuda.conv and slayercuda.spike

**Comment by bamsumit** [comment]
Can you confirm that all the unittests passed after installation? Instructions [here](https://github.com/bamsumit/slayerPytorch#installation).

**Comment by kkkkkkip** [comment]
Sorry I didn't test before, and now I have a lot of errors after testing:
Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
..F.FF......FF..F..F...FFFFFF....
======================================================================
FAIL: testOut (test_slayer002.testSpike)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer002.py", line 198, in testOut
    self.assertEqual(torch.norm(spikeGT - spikeOut), 0, 'Error mus be zero.')
AssertionError: tensor(153.4171, device='cuda:0', grad_fn=<CopyBackwards>) != 0 : Error mus be zero.

======================================================================
FAIL: test (test_slayer003.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer003.py", line 101, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

======================================================================
FAIL: test (test_slayer004.testSpikeClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer004.py", line 74, in test
    self.assertEqual(predict.getClass(spikeOut), 21, 'Correct class is 21.')
AssertionError: tensor([24]) != 21 : Correct class is 21.

======================================================================
FAIL: testShift (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer009.py", line 81, in testShift
    self.assertEqual(netError, 0, 'Shift error must be zero.')
AssertionError: 667636.7356815338 != 0 : Shift error must be zero.

======================================================================
FAIL: testShiftPerNeuron (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer009.py", line 63, in testShiftPerNeuron
    self.assertEqual(netError, 0, 'Shift (per neuron) error must be zero.')
AssertionError: 667314.8420734406 != 0 : Shift (per neuron) error must be zero.

======================================================================
FAIL: test (test_slayer011.TestPspLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer011.py", line 43, in test
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp layer must match.')
AssertionError: tensor(False, device='cuda:0') is not true : Result from Psp function and Psp layer must match.

======================================================================
FAIL: testValues (test_slayer012.TestPspFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayer012.py", line 53, in testValues
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp filter bank must match.')
AssertionError: tensor(False, device='cuda:0') is not true : Result from Psp function and Psp filter bank must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiSpikes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayerLoihi001.py", line 123, in testOutput
    self.assertTrue(error<1e-3, 'Output spike and ground truth must match.')
AssertionError: False is not true : Output spike and ground truth must match.

======================================================================
FAIL: testHidden (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayerLoihi001.py", line 129, in testHidden
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayerLoihi001.py", line 133, in testOutput
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

======================================================================
FAIL: testCurrent (test_slayerLoihi002.testRefDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayerLoihi002.py", line 126, in testCurrent
    self.assertTrue(error<1e-3, 'Current: cuda ouptut and ground truth must match.')
AssertionError: False is not true : Current: cuda ouptut and ground truth must match.

======================================================================
FAIL: testSpikes (test_slayerLoihi002.testRefDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayerLoihi002.py", line 116, in testSpikes
    self.assertTrue(error<1e-3, 'Spikes: cuda ouptut and ground truth must match.')
AssertionError: False is not true : Spikes: cuda ouptut and ground truth must match.

======================================================================
FAIL: testVoltage (test_slayerLoihi002.testRefDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kexin/Downloads/spike0test/EventStream-SR-main/slayerPytorch-master/test/test_slayerLoihi002.py", line 121, in testVoltage
    self.assertTrue(error<1e-3, 'Voltage: cuda ouptut and ground truth must match.')
AssertionError: False is not true : Voltage: cuda ouptut and ground truth must match.

----------------------------------------------------------------------
Ran 33 tests in 11.572s

FAILED (failures=13)

My environment:
torch version: 1.7.0
CUDA Version: 10.1
nvcc version: 10.1
GCC version: 7.3

Do not know why the installation test error, want to get your help

**Comment by kkkkkkip** [comment]
after read #50（same situation） ,I change the driver cuda11.0 and the nvcc compiler 11.1
gcc 9.3.0   cudatoolkit11.0 
pytorch 1.7.1     py3.7_cuda11.0.221_cudnn8.0
But the same error was reported
FAILED (failures=13)

**Comment by kkkkkkip** [comment]
I've tried reinstalling several environments using anaconda, but it's always the same problem

**Comment by bamsumit** [comment]
What is the make of your GPU?

**Comment by kkkkkkip** [comment]
Teska V100

**Comment by kkkkkkip** [comment]
Because I don't have root, it is difficult to use docker. Is there any other way to solve my testing problem

**Comment by kkkkkkip** [comment]
Hello, finally, I successfully completed all tests by obtaining root configuration docker. Thank you very much for your help

**Comment by bamsumit** [comment]
Great. Thanks for letting us know.
