### ISSUE TITLE
Relation between this repository and the original C++ implementation

### ISSUE THREAD

**Issue by zhangsen-hit** [bamsumit/slayerPytorch#104]
Does this PyTorch implementation rely on the original version? Is it an independent implementation that has been re-implemented using PyTorch?

**Comment by bamsumit** [comment]
Hi @zhangsen-hit this implementation uses some of the accelerated components from the original C++ implementation. This version is more feature-rich. You might want to look at [Lava-DL](https://github.com/lava-nc/lava-dl) SLAYER for even more feature-rich version.

**Comment by zhangsen-hit** [comment]
Thank you very much! I have noticed that Lava-DL SLAYER provides more neuron models and other useful features, which is highly beneficial.

Here I have another question. In both this repository and Lava-DL SLAYER, the input and output data types are tensors in the format [NCHWT] or [NCT], where 'T' represents the time dimension and is placed at the end. So, during the forward propagation process, is the computation performed layer by layer, rather than time step by time step? Can we obtain the results of any time steps before the entire forward propagation is finished?

**Comment by bamsumit** [comment]
@zhangsen-hit slayerPyTorch computes the output of each layer for all the timesteps at once. Lava-dl SLAYER allows for both options. By default, it calculates the output of all the outputs at once, but all neuron models have `persistent_mode` flag. When you set it, you can execute the entire network one time-step at a time if needed.

**Comment by zhangsen-hit** [comment]
I could not find the term `persistent_mode` in the source code, but I did find `persistent_state`. Are you referring to `persistent_state`?

Furthermore, upon reviewing the source code of lava-dl, I did not find the SRM neuron mentioned in the original paper [SLAYER](https://proceedings.neurips.cc/paper/2018/hash/82f2b308c3b01637c607ce05f52a2fed-Abstract.html) and implemented in slayerPytorch. Could you please clarify why this neuron type was abandoned?  Or, was the name 'SRM' replaced with another term?
