### ISSUE TITLE
Something about load IBMGestrure dataset

### ISSUE THREAD

**Issue by hewh16** [bamsumit/slayerPytorch#11]
Hi~
I'm an undergraduate of Tsinghua University, and working for dvs gesture datasets. I try to load the dataset as your framework but, where is the sample file? I guess the datasetPath is where the raw dataset at, but I haven't got any sample file named train.txt or test.txt. Can you show me where they are and how to use them? Thanks:)

**Comment by bamsumit** [comment]
Hi,
You will have to pre-process the dataset from the raw dvsgesture data from IBM. You will also have to create the sample split to generate train.txt and test.txt and modify your dataloader accordingly.
Refer to https://github.com/bamsumit/slayerPytorch/issues/10#issuecomment-549216709 for template code for how it can be done (THE CODE IS NOT TESTED THOUGH).
