### ISSUE TITLE
Desired_10_60 flies in MNIST dataset

### ISSUE THREAD

**Issue by Zhikai-Huang** [bamsumit/slayerPytorch#19]
Hello! I am in the beginning phase to learn SLAYER. I run the NMINST examples after installing SLAYER. I find desired_10_60 files in NMNISTsmall.zip are confusing, what are these files used for? I rerun the code without these files, and I can still get the result accuracy of ~99%. So I think these files are not useful in training, correct?

Thanks 
Zhikai

**Comment by bamsumit** [comment]
Those files are not used in PyTorch version of SLAYER.
