### ISSUE TITLE
can it runs in Windows?

### ISSUE THREAD

**Issue by hisrg** [bamsumit/slayerPytorch#2]
Hello, Cant it runs in Windows?

**Comment by bamsumit** [comment]
Hi, we haven't tested it on Windows system. In principle, it should run on windows as long as you have cuda and PyTorch properly running. I will be happy to help if you face any issues.
Regards

**Comment by sylvain-bougnoux** [comment]
I could make it run. But there is an issue with pytorch installation. Just follow 
https://github.com/pytorch/extension-cpp/issues/37
(actually I left the "return" in the last fix). 
Now at least the test run fine.

**Comment by bamsumit** [comment]
Thanks mate for working it out. Since it passed the unittests, it should be fine. Let me know if you face any issues in using it or even if it works as expected. Then I will add the instruction in main page so that other windows users can also benefit.
Best,
Sumit

**Comment by sylvain-bougnoux** [comment]
Among the examples (tested from the console with python *.py):
01 works
02 & 03 fails in the multiprocessing version of the dataloader
 ```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Program Files\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Contrib\slayerPytorch\example\03_NMNIST_CNN\nmnistCNN.py", line 113, in <module>
    for i, (input, target, label) in enumerate(trainLoader, 0):
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
But I am afraid it is more a torch issue...

**Comment by bamsumit** [comment]
Yes it looks like a problem of multiprocessing module on windows. 

[This](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) blog post says if you write the executable portion of the code under 
```
if __name__ == '__main__':
    executable_code ...
```
the problem does not happen. Worth a try.

I guess if you use num_workers=1 in dataloaders, it should not be a problem as well.

**Comment by sylvain-bougnoux** [comment]
I've already tried without success with ```num_workers = 1```

For your second trick (```if __name__ ...```), it is much better. I only got
```
Traceback (most recent call last):
  File "nmnistMLP.py", line 123, in <module>
    stats.training.correctSamples += torch.sum( snn.predict.getClass(output) == label ).data.item()
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'other'
```

**Comment by bamsumit** [comment]
Can you try changing the line to this:
```
stats.training.correctSamples += torch.sum( snn.predict.getClass(output) == label.long() ).data.item()
```

**Comment by sylvain-bougnoux** [comment]
Very good. 03 works (epoch not yet finished but running)
(just note that there are 2 such lines for train & test).
I will try 02

**Comment by bamsumit** [comment]
Does it work even with num_workers > 1?

**Comment by sylvain-bougnoux** [comment]
> Does it work even with num_workers > 1?

Yes

**Comment by sylvain-bougnoux** [comment]
For 03 I had to change
```
device = torch.device('cuda:2') # should be the first GPU of deviceIDs
deviceIds = [2, 3, 1]
```
into (I have only one GTX1080)
```
device = torch.device('cuda') # should be the first GPU of deviceIDs
deviceIds = [0]
```
It is working but it is very slow. Strangely the GPU is not used (2%, 1min10/epoch), another torch issue?

**Comment by bamsumit** [comment]
Since you have only one GPU, can you change line 70-79 to. It will remove extra management overhead of having to spawn and gather.
```
# Define the cuda device to run the code on.
device = torch.device('cuda')

# Create network instance.
net = Network(netParams).to(device)
```

**Comment by sylvain-bougnoux** [comment]
Thanks but it does not change anything. About 80s per epoch (for 03).
```torch.cuda.is_available()``` is true.
On a Linux machine, same GPU, one epoch takes about 28s.

**Comment by bamsumit** [comment]
Let me know if you figure something out.
Thanks a lot for testing things out though. Appreciate it.

**Comment by bamsumit** [comment]
__FIX__ that worked for me
-  In `argument_spec.h`,
    - replace `static constexpr size_t DEPTH_LIMIT = 128;` with `static const size_t DEPTH_LIMIT = 128;`
- In `module.h`,
    - replace __ALL__ the instances of `static constexpr bool all_slots = false;` with `static const bool all_slots = false;`
- In `cast.h`,
    - replace `explicit operator type&() { return *(this->value); }` with `explicit operator type& () { return *((type*)(this->value)); }`
If you search for error in compilation log, it will show the lines and files that need to be changed. The line number may change from version to version.

After this fix, everything is running as expected, as fast as in ubuntu.
