### ISSUE TITLE
Python unit tests failing

### ISSUE THREAD

**Issue by sms821** [bamsumit/slayerPytorch#23]
Environment:
OS: Ubuntu 16.04
Pytorch, Cuda: 1.0.1, 9.2 (conda build)
Python: 3.7.6
System GPU driver and cuda toolkit version: 418.87, 10.1
Hello @bamsumit,
I am trying to understand the SLAYER algorithm and framework. As per the instructions, I downloaded the repository and ran `python setup.py install` which seemed to go fine.
However, the unit tests are failing and I am not sure why. All test cases have the same `undefined symbol` error as shown below:
<img width="1440" alt="Screen Shot 2020-05-28 at 5 10 25 PM" src="https://user-images.githubusercontent.com/24283722/83194336-7b603600-a106-11ea-96fa-88d4ad765977.png">

Please help.

**Comment by bamsumit** [comment]
It looks like a linker error. Your GPU driver is for cuda 10.1 and your PyTorch installation is for cuda 9.2. Make sure the cuda compiler and the driver version are same.
