### ISSUE TITLE
Running SLAYER on the Loihi

### ISSUE THREAD

**Issue by jethrokuan** [bamsumit/slayerPytorch#25]
Hi, I've been trying to run the slayer on the Loihi, and I noticed some inconsistencies with the output from the examples, and the required inputs on the Intel Loihi side of things. Since that side of things is confidential, I'm keeping the discussion here at a higher level.

I have trained a model with SLAYER that has decent performance (say, 0.8) with quantized weights. Post #24 , I can confirm that the GPU simulation of Loihi gives the same desired result of 0.8 by loading the quantized weights. However, I cannot reproduce this number on the Loihi.

One question I have is with regards to the shape of the input. In https://github.com/bamsumit/slayerPytorch/blob/master/exampleLoihi/02_NMNIST/nmnistTrain.py#L77, the weights are quantized, flattened and saved, resulting in a 1d array. However, the required input dimensions on the Loihi side are `(output_size, input_size)`. I've tried:

1. Reshape to `(input_size, output_size)`, and `swapaxes` to get `(output_size, input_size)`, and
2. Reshape to `(output_size, input_size)`

Both yield poor results. Could you let me know how the saved weights for running on the Loihi are generated?

**Comment by bamsumit** [comment]
Hi, the weights must be reshaped to `(output_size, input_size)`. In fact, you can squeeze the weight and save it as a numpy matrix and directly load later.

- By _loading the quantized weights in Loihi_, do you mean you load the weight values individually rather than using PyTorch saved model (`*.pt`)?
- If you are using some weight modifier like weight normalization, make sure to remove them.
- Finally have you checked your input spikes? Make sure the spike events are sorted in time. This is not necessary for SLAYER in GPU, but it may cause loss of spikes in Loihi.

**Comment by jethrokuan** [comment]
Thank you for getting back.

> the weights must be reshaped to `(output_size, input_size)`

Gotcha.

> By loading the quantized weights in Loihi, do you mean you load the weight values individually rather than using PyTorch saved model (*.pt)?

Yes, I use the same quantization procedure in the code example in this repo, and reshape it to the correct size, finally following the slayer2Loihi tutorial of setting the proto's `weightFile`. To the reshaped `.npy` file. Is there a way of loading the pytorch model directly?

> If you are using some weight modifier like weight normalization, make sure to remove them.

I don't think this is in use anywhere.

> Finally have you checked your input spikes? Make sure the spike events are sorted in time. This is not necessary for SLAYER in GPU, but it may cause loss of spikes in Loihi.

I have 1 question about this: In that code, an event consists of x,y,p,t. My spiking inputs are 1 dimensional, of the form `(num_inputs, seq_length)` with 1s where a spike occurs and 0 where there isn't one. I've massaged the input data in this form:

```
        self.data = np.load(filename).reshape(input_size, -1)
        idx, time = np.where(self.data == 1)
        order = time.argsort()
        idx = idx[order]
        time = time[order]
        self.p = np.zeros(len(idx), dtype="uint64")
        self.t = np.zeros(len(idx), dtype="uint64")
        self.x = np.zeros(len(idx), dtype="uint64")
        self.y = np.zeros(len(idx), dtype="uint64")
        
        # p is always 0, and y is always 0
        for i in range(len(idx)):
            self.x[i] = idx[i]
            self.t[i] = time[i]
```

so the spiking events are sorted by time, `p` and `y` are always 0, and `x[i]` is the index for the spiking input. Does this look fine to you, or do you think this would affect the results?

Finally, let me know if you would like to take this offline via email.

**Comment by bamsumit** [comment]
It looks fine to me. Sure, you can email me.
