### ISSUE TITLE
setup.py is incompatible with newer PIP

### ISSUE THREAD

**Issue by joehays** [bamsumit/slayerPytorch#26]
I frequently use,

`pip install -e .`

after I have cloned a repo in case I want to experiment. However, a recent PIP upgrade broke that ability with SLAYER. The scenario and explanation is documented here:

https://github.com/pypa/pip/issues/8201

SLAYER's setup.py generates 3 egg-info files which appears to be unsupported going forward.

**Comment by bamsumit** [comment]
Hi @joehays,

Suggest a solution. Combining all the compilation into a single egg will require some modification to the modules.

Anyway, what is the problem with `python setup.py install`?
