### ISSUE TITLE
Error occurs when "python setup.py install" in Windows

### ISSUE THREAD

**Issue by hyeongilee** [bamsumit/slayerPytorch#27]
Hi, I'm trying to run setup.py in Windows. And my environment is 

-Windows 10
-CUDA 9.2
-CUDNN 7.1
-PyTorch 1.5.1

but the following error occurs.

![image](https://user-images.githubusercontent.com/45928371/86031032-441bd680-ba70-11ea-80a6-b9e462670a09.png)

And I looked https://github.com/bamsumit/slayerPytorch/issues/22#issue-617970861 , but I couldn't find a solution.
I tried https://github.com/pytorch/extension-cpp/issues/37#issuecomment-515698094 , but nothing changed.

**Comment by bamsumit** [comment]
See [this](https://github.com/bamsumit/slayerPytorch/issues/2#issuecomment-582315606) fix for running SLAYER in Windows.

By the way, first line of your error says __no CUDA runtime found__ !

**Comment by bamsumit** [comment]
Hi, is your issue solved?

**Comment by hyeongilee** [comment]
I couldn't solve the problem, but I'm using it successfully since it worked in a linux environment. Thanks.
