### ISSUE TITLE
Error on running setup.py on windows

### ISSUE THREAD

**Issue by Lind-IndustrialControl** [bamsumit/slayerPytorch#28]
Hello, I am a graduate student from Peking University. I am having problems reproducing your example, please ask for your help！
like this：
\anaconda3\envs\pytorch\lib\site-packages\torch\include\pybind11\cast.h(1900): error: no instance of overloaded function "pybind11::detail::concat" matches the argument list
            argument types are: (pybind11::detail::descr<12ULL>, pybind11::detail::descr<12ULL>, pybind11::detail::descr<7ULL>)
          detected during:
            instantiation of class "pybind11::detail::argument_loader<Args...> [with Args=<at::Tensor, at::Tensor, float>]"

**Comment by bamsumit** [comment]
Hi, please provide details of your OS, CUDA version (both runtime and compiler), and PyTorch version.
