### ISSUE TITLE
About running 03_IBMGesture 

### ISSUE THREAD

**Issue by Lind-IndustrialControl** [bamsumit/slayerPytorch#29]
Hi, When I 
->python ibmGestureTrain.py
something wrong like this:
/neuromorphic/shared/Datasets/IBMGesture/DvsGesture_converted_to_bs2_1450/train.txt not found.
How to get this text?
Thanks~

**Comment by ZY-SS-PKU** [comment]
@bamsumit I have the same question，and was stuck here. Thanks for your contribution.

**Comment by bamsumit** [comment]
Hi, 
It is not possible to include the whole DVS Gesture dataset here. You will have to do the required preprocessing to the original data.   Follow this script [here](https://github.com/bamsumit/slayerPytorch/issues/10#issuecomment-549216709). YOU MIGHT NEED TO MODIFY A FEW THINGS.
