### ISSUE TITLE
Neuromorphic datasets

### ISSUE THREAD

**Issue by tehreemnaqvi** [bamsumit/slayerPytorch#30]
Hi,

 I just started to work on Neuromorphic datasets.

I am using the PyTorch framework for SNN and using your reference codes.

But I am confused about how to read spikes in PyTorch dataloders because you used a slayer framework to read spikes.
Can you please tell me how I read spikes using PyTorch dataloader.

Your help will be appreciated.

Thanks

**Comment by bamsumit** [comment]
I didn't get what you are saying. The examples use PyTorch dataloader! As for reading spikes in the dataset module, you can use any method to replace slayer spike read methods.
