### ISSUE TITLE
Slayer Installation

### ISSUE THREAD

**Issue by tehreemnaqvi** [bamsumit/slayerPytorch#31]
Hi, 
I tried to install SLAYER software using python step.py install but got many errors.
How can I install it correctly?

Thanks

**Comment by bamsumit** [comment]
Description of the nature of error would be useful.

**Comment by tehreemnaqvi** [comment]
![image](https://user-images.githubusercontent.com/38427571/87779890-8a42a980-c868-11ea-9081-cc591c373ef5.png)

**Comment by bamsumit** [comment]
Looks like your installation step had errors.

**Comment by tehreemnaqvi** [comment]
First I clone the repository and used this one:
![image](https://user-images.githubusercontent.com/38427571/87780158-1ce34880-c869-11ea-99f3-ff1377402779.png)

**Comment by bamsumit** [comment]
Try this [fix](https://github.com/bamsumit/slayerPytorch/issues/2#issuecomment-582315606) for windows.
