### ISSUE TITLE
IBM gesture dataset don't find

### ISSUE THREAD

**Issue by albertopolito** [bamsumit/slayerPytorch#36]
Good morning,
I'm newbie. I run the example ibmGestureTrain.py , but it seems that don't find the IBM gesture dataset.
I download the original dataset from the official page and put it in the same folder of the python code. 
Thanks.

**Comment by bamsumit** [comment]
You have to download and preprocess the dataset yourself. Refer [here](https://github.com/bamsumit/slayerPytorch/issues/10#issuecomment-549216709) for template code.
