### ISSUE TITLE
Unittest - Memory overflow and false computation

### ISSUE THREAD

**Issue by rogergermann** [bamsumit/slayerPytorch#39]
I succesfully could install slayerPytorch after fixing the bugs appearing in pytorch reported in #2 which appear in Windows. Unfortunately I get memory overflow errors in the graphic card and afterwards also false computation in the later unittest (full report below). 

Has anyone an idea what might be not working?

System:
- Windows 10, 16GB Ram
- GTX965M (Cuda 10 compatible), 4GB On-Card Memory
- Cuda 10.1 & Fitting CuDNN (cudnn-10.1-windows10-x64-v8.0.2.39)
- Anaconda
- Tried with PyTorch 1.4 and 1.6 (conda install)

Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
..F.FF....E.FF..F..FEE.FFF....
======================================================================
ERROR: testOddDimension (test_slayer007.TestPooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer007.py", line 78, in testOddDimension
    out = pool(inTensor)
  File "C:\Users\Roger\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Roger\anaconda3\lib\site-packages\slayersnn-0.0.0-py3.8.egg\slayerSNN\slayer.py", line 574, in forward
    input = torch.cat((input, torch.zeros((input.shape[0], input.shape[1], input.shape[2]%self.weight.shape[2], input.shape[3], input.shape[4]), dtype=dtype).to(device)), 2)
RuntimeError: CUDA out of memory. Tried to allocate 630.00 MiB (GPU 0; 4.00 GiB total capacity; 2.62 GiB already allocated; 234.80 MiB free; 2.79 GiB reserved in total by PyTorch)

======================================================================
ERROR: test (test_slayer013.TestConvTranspose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer013.py", line 36, in test
    outGT = torch.zeros((N, C, H+K-1, W+K-1, D)).to(device)
RuntimeError: CUDA out of memory. Tried to allocate 662.00 MiB (GPU 0; 4.00 GiB total capacity; 2.23 GiB already allocated; 234.80 MiB free; 2.79 GiB reserved in total by PyTorch)

======================================================================
ERROR: test (test_slayer013.TestUnpooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer013.py", line 71, in test
    outGT[:, :, 0::2, 0::2, :] = inTensor * 1.1 * netParams['neuron']['theta']
RuntimeError: CUDA out of memory. Tried to allocate 154.00 MiB (GPU 0; 4.00 GiB total capacity; 2.90 GiB already allocated; 80.80 MiB free; 2.94 GiB reserved in total by PyTorch)

======================================================================
FAIL: testOut (test_slayer002.testSpike)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer002.py", line 196, in testOut
    self.assertEqual(torch.norm(spikeGT - spikeOut), 0, 'Error mus be zero.')
AssertionError: tensor(175.6756, device='cuda:0', grad_fn=<NormBackward0>) != 0 : Error mus be zero.

======================================================================
FAIL: test (test_slayer003.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer003.py", line 100, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

======================================================================
FAIL: test (test_slayer004.testSpikeClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer004.py", line 72, in test
    self.assertEqual(predict.getClass(spikeOut), 21, 'Correct class is 21.')
AssertionError: tensor([1]) != 21 : Correct class is 21.

======================================================================
FAIL: testShift (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer009.py", line 81, in testShift
    self.assertEqual(netError, 0, 'Shift error must be zero.')
AssertionError: 13193244.289892197 != 0 : Shift error must be zero.

======================================================================
FAIL: testShiftPerNeuron (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer009.py", line 63, in testShiftPerNeuron
    self.assertEqual(netError, 0, 'Shift (per neuron) error must be zero.')
AssertionError: 13186330.843816757 != 0 : Shift (per neuron) error must be zero.

======================================================================
FAIL: test (test_slayer011.TestPspLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer011.py", line 43, in test
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp layer must match.')
AssertionError: tensor(False, device='cuda:0') is not true : Result from Psp function and Psp layer must match.

======================================================================
FAIL: testValues (test_slayer012.TestPspFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayer012.py", line 53, in testValues
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp filter bank must match.')
AssertionError: tensor(False, device='cuda:0') is not true : Result from Psp function and Psp filter bank must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiSpikes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayerLoihi001.py", line 123, in testOutput
    self.assertTrue(error<1e-3, 'Output spike and ground truth must match.')
AssertionError: False is not true : Output spike and ground truth must match.

======================================================================
FAIL: testHidden (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayerLoihi001.py", line 129, in testHidden
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...pytorch\\test\test_slayerLoihi001.py", line 133, in testOutput
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

----------------------------------------------------------------------
Ran 30 tests in 34.904s

FAILED (failures=10, errors=3)

**Comment by bamsumit** [comment]
The issue is your GPU models have cuda compute capability less than 6. Here is what you need to do. In `setup.py`, look for  `-arch=sm_60` and replace it with `-arch=sm_50`

**Comment by rogergermann** [comment]
I reinstalled anaconda and adjusted the setup file as you suggested. The fail "FAIL: testHidden (test_slayerLoihi001.testLoihiVoltage)" is no longer present, the others still unfortunately.

**Comment by bamsumit** [comment]
Are you sure, you replaced all of the instances? Some of the errors are due to the GPU memory limit, which cannot be solved. Let's look at the problems one by one: try this and post the program output and figures.
```
cd test/
python test_slayer002.py --verbose
```

**Comment by rogergermann** [comment]
I uninstalled anaconda today again, the files in the program data folder was gone (there I changed the pytorch lines). The residue files in %appdata% I deleted manually (didn't seem to hold anything relevant for slayerPytorch).

Reinstalling anaconda with pytorch v1.4.0 and rerunning all unittest resulted in the same Error/Fails as with pytorch v1.6.0. I also run the anaconda prompt with admin priviledges to see if it may be due to read/write restrictions, no change.

- Running with the verbose option results in this (except timing same for pytorch v1.4.0 and v1.6.0):

> (base) ...\02_slayer_pytorch\test>python test_slayer002.py --verbose
> Spike Load Error: 0.0
> (500,)
> (160,)
> testHid (__main__.testSpike) ... ok
> testOut (__main__.testSpike) ... FAIL
> test (__main__.testSpikeLoad) ... ok
> 
> ======================================================================
> FAIL: testOut (__main__.testSpike)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_slayer002.py", line 196, in testOut
>     self.assertEqual(torch.norm(spikeGT - spikeOut), 0, 'Error mus be zero.')
> AssertionError: tensor(107.2391, device='cuda:0', grad_fn=<NormBackward0>) != 0 : Error mus be zero.
> 
> ----------------------------------------------------------------------
> Ran 3 tests in 0.039s
> 
> FAILED (failures=1)




- For test_slayer003.py (pytorch v1.4.0):


> (base) C:\Users\Roger\Google Drive\02_Studium\Semesterproject\04_Software\02_slayer_pytorch\test>python test_slayer003.py --verbose
> loss : tensor(0., grad_fn=<CopyBackwards>)
> Layer2 gradient error : 0.5373003744838449
> Layer1 gradient error : 0.0025695202466353216
> test (__main__.testGradients) ... FAIL
> 
> ======================================================================
> FAIL: test (__main__.testGradients)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_slayer003.py", line 100, in test
>     self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
> AssertionError: False is not true : Error must be close to zero.
> 
> ----------------------------------------------------------------------
> Ran 1 test in 0.001s
> 
> FAILED (failures=1)

**Comment by bamsumit** [comment]
It should also generate some plots

**Comment by rogergermann** [comment]
> It should also generate some plots

There weren't any. Could it have something to do with the Anaconda Prompt?

**Comment by bamsumit** [comment]
Do you get figure output from `matplotlib` in your system?

**Comment by rogergermann** [comment]
Dear Sumit

It is a bit embarrassing but your first hint was actually all that would be necessary. After hours I now figured out, that I only have changed it in one place instead both. After reinstalling with both lines adjusted, the unittest passes (except the memory overflows).

Thank you very much for your help and sorry that I didn't notice it earlier!
