### ISSUE TITLE
Use of Slayer on the Loihi for lane detection

### ISSUE THREAD

**Issue by albertopolito** [bamsumit/slayerPytorch#42]
Goodmorning, I'm a newbie and I study how to use the Loihi for autonomous driving. I'm in the INRC group. 
I would use, in some way, your learning rule to detect the street lane using the DET dataset on the link: [https://spritea.github.io/DET/](url). In these dataset the image are the sipke accumulation of a DVS camera events between 30 ms.
My idea is to do something like your "Oxford example" on the Loihi. The input of the network receive the image as in the input of the Oxford example (so the input neurons can be 1280 as the x spatial resolution and the "spike time of the image is of 8,00 ms, because the spatial y resolution is of 800 pixel and every 30 ms there is a new image"). The backend of the network can have also 1280 neurons (as the x resolution of the label image) and the prediction image takes 8,00 ms. 
I don't know if this is a good idea for these reasons:

1) the loss criterion used is based on spike time, but I want that the network change the spike time on the output according to the different input images. In the Oxford example the input image is the same and the network learn only one possibility on the output.
2) in the Loihi the time of the predicted image of 8,00 ms is too small, in your opinion it is feasible and it can achieve a good accuracy? I use 8 ms because every 30 ms we have new image and I use the first 8 ms to give the input image and other 8 ms to take the prediction on the output, and save some time (14 ms) for the possible use of the prediction before the new image.

In your opinion it can be feasible? It is a good idea or there can be some other possibility?
Thank a lot for your time,
Best regards.

**Comment by bamsumit** [comment]
Hi, let's take this conversation in email.

**Comment by albertopolito** [comment]
Sorry, I don't know if I have to write my email account here, but I don't find yours.
So my email is: alberto.viale@tuwien.ac.at 
Can you contact me on this email address.
Thanks.
Best regards.
