### ISSUE TITLE
Can Loihi do regression task?

### ISSUE THREAD

**Issue by Originofamonia** [bamsumit/slayerPytorch#44]
Hi,

I was trying to use SlayerLoihi to do a regression task. I wrote the code based upon SlayerLoihi NMNIST. However, the outputs of my regression task are all 0s. So I have a few questions about the feasibility of using Loihi to do the regression task.
1. Does Loihi only support outputting spike counts?
2. If no, how does Loihi output numeric values and negative values?

Thanks!

**Comment by bamsumit** [comment]
Short answer is Yes. Let's take this conversation in email or in INRC page.

**Comment by Originofamonia** [comment]
Hi,

Thanks for your reply.
Could you please provide some materials so I can read to get started on Loihi doing regression problems? I’m also in INRC community.
I don’t know your email. Mine is anqiyuan@vt.edu<mailto:anqiyuan@vt.edu>.

Thanks,
Qiyuan
