### ISSUE TITLE
4 errors detected in the compilation of "C:/Users/24394/AppData/Local/Temp/tmpxft_0000f1cc_00000000-10_slayerKernels.cpp1.ii". error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 1

### ISSUE THREAD

**Issue by lyccong** [bamsumit/slayerPytorch#48]
Hello Great guys,
When I tried to install slayerPytorch in Windows 10, I got the follow compilation error in the last step, anyone can have a look? Thanks

running install
running bdist_egg
running egg_info
writing slayerCuda.egg-info\PKG-INFO
writing dependency_links to slayerCuda.egg-info\dependency_links.txt
writing top-level names to slayerCuda.egg-info\top_level.txt
reading manifest file 'slayerCuda.egg-info\SOURCES.txt'
writing manifest file 'slayerCuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\24394\anaconda3\envs\stbp\lib\site-packages\torch\utils\cpp_extension.py:209: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'slayerCuda' extension
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe -c src/cuda/slayerKernels.cu -o build\temp.win-amd64-3.6\Release\src/cuda/slayerKernels.obj -IC:\Users\24394\anaconda3\envs\stbp\lib\site-packages\torch\include -IC:\Users\24394\anaconda3\envs\stbp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\24394\anaconda3\envs\stbp\lib\site-packages\torch\include\TH -IC:\Users\24394\anaconda3\envs\stbp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\24394\anaconda3\envs\stbp\include -IC:\Users\24394\anaconda3\envs\stbp\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0
slayerKernels.cu
C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/Exception.h(28): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/Exception.h(29): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/Exception.h(30): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/Exception.h(35): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/Exception.h(36): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/Allocator.h(21): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/Allocator.h(183): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/typeid.h(460): warning: dllexport/dllimport conflict with "caffe2::TypeMeta::_typeMetaDataInstance [with T=caffe2::detail::_Uninitialized]"
(456): here; dllexport assumed

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/intrusive_ptr.h(63): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/intrusive_ptr.h(64): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/Storage.h(181): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorTypeSet.h(44): warning: integer conversion resulted in a change of sign

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/impl/LocalTensorTypeSet.h(50): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/impl/LocalTensorTypeSet.h(51): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/logging_is_not_google_glog.h(47): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(224): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(1560): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(1563): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(1585): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(1586): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(1611): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/core/TensorImpl.h(1630): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/Generator.h(75): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/NamedTensor.h(53): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/TensorBody.h(1104): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(118): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(138): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(139): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(188): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(200): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(210): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(301): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(302): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(303): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(306): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(307): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(313): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(389): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(390): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(370): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(617): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(618): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(621): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(633): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(748): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(797): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(879): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(881): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(1574): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(1575): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(1577): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(1581): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(1584): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/jit_type.h(1639): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/boxing/KernelFunction.h(375): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/boxing/KernelFunction.h(376): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(132): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(133): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(134): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(135): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(136): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(164): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/CPUGenerator.h(32): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/CPUGenerator.h(33): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/CPUGenerator.h(34): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/Context.h(124): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/Context.h(125): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/Context.h(130): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/Context.h(131): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/Context.h(132): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/TensorGeometry.h(56): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/TensorGeometry.h(57): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/TensorNames.h(42): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\ATen/TensorNames.h(72): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/autograd/variable.h(180): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/autograd/variable.h(183): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/autograd/variable.h(184): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/autograd/variable.h(186): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/autograd/variable.h(187): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/autograd/variable.h(203): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/tracer.h(49): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/tracer.h(52): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/tracer.h(85): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/tracer.h(181): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/tracer.h(289): warning: dllexport/dllimport conflict with "torch::jit::tracer::addInputs"
(277): here; dllexport assumed

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/tracer.h(293): warning: dllexport/dllimport conflict with "torch::jit::tracer::addInputs"
(283): here; dllexport assumed

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/attributes.h(95): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/attributes.h(109): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/attributes.h(112): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/attributes.h(126): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/source_range.h(169): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/scope.h(25): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/scope.h(87): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/constants.h(20): warning: base class dllexport/dllimport specification differs from that of the derived class

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/operator.h(166): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/operator.h(170): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/operator.h(174): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/operator.h(176): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/operator.h(177): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(245): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(246): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(248): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(251): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(252): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(253): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\torch/csrc/jit/ir.h(778): warning: field of class type without a DLL interface used in a class with a DLL interface

C:/Users/24394/anaconda3/envs/stbp/lib/site-packages/torch/include\c10/util/BFloat16.h(48): warning: calling a __host__ function from a __host__ __device__ function is not allowed

src/cuda/slayerKernels.cu(136): error: identifier "slayerCuda" is undefined

src/cuda/slayerKernels.cu(136): error: identifier "m" is undefined

src/cuda/slayerKernels.cu(136): error: explicit type is missing ("int" assumed)

src/cuda/slayerKernels.cu(138): error: identifier "m" is undefined

src/cuda/slayerKernels.cu(145): warning: missing return statement at end of non-void function "PYBIND11_MODULE"

4 errors detected in the compilation of "C:/Users/24394/AppData/Local/Temp/tmpxft_0000f1cc_00000000-10_slayerKernels.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 1

How to fix these errors? I tried a lot but couldn't install SLAYER.

Thanks

**Comment by bamsumit** [comment]
Have you tried this [fix](https://github.com/bamsumit/slayerPytorch/issues/2#issuecomment-582315606)?

**Comment by lyccong** [comment]
thank you，I have solved the above problem。But I  encountered a new problem：

(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example/02_NMNIST_MLP# python nmnistMLP.py
Epoch :         99(i =      10),   11809.7060 ms elapsed
loss = 0.038517    (min = 0.040218   )    accuracy = 1        (max = 1       )
loss = 1.1899      (min = 1.0625     )    accuracy = 0.90909  (max = 0.96    )
(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example/02_NMNIST_MLP# 
(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example/02_NMNIST_MLP# cd ..
(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example# ls
01_Oxford  02_NMNIST_MLP  03_NMNIST_CNN
(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example# cd 03_NMNIST_CNN/
(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example/03_NMNIST_CNN# ls
NMNISTsmall.zip  network.yaml  nmnistCNN.ipynb  nmnistCNN.py
(py37) root@efcfef7005fc5011eb09fc3073a5b73883c3-liyc222-0-0-0:/userhome/slayerPytorch-master/slayerPytorch-master/example/03_NMNIST_CNN# python nmnistCNN.py
Epoch :         99(i =       8),   42184.1410 ms elapsed
loss = 0.071942    (min = 0.072452   )    accuracy = 1        (max = 1       )
loss = 2.6177      (min = 2.5208     )    accuracy = 0.66     (max = 0.7     )

The above nmnistCNN.py and nmnistMLP.py programs both stopped at Epoch 99 and exited。And there is no result graph。Can I ask how to solve this problem？Thanks

**Comment by bamsumit** [comment]
Are you sure your matplotlib is working properly? The code does not save any figures. The figures should pop up.

**Comment by lyccong** [comment]
Thanks for your answer。Now I can see the figures by add plt.savefig to the code.
