### ISSUE TITLE
Foward instead of forward

### ISSUE THREAD

**Issue by Huizerd** [bamsumit/slayerPytorch#5]
I guess this typo could lead to an inherited `forward()` method being called instead of the one in `_convLayer`?

https://github.com/bamsumit/slayerPytorch/blob/3364998b440ec3deeab1eeb6c55779441e96a2b0/src/slayer.py#L431

**Comment by bamsumit** [comment]
Hi Huizerd,
Thanks for finding it. Yes it calls the base class's forward routine. Fortunately, they are same for convLayer :). I have fixed it though.
Regards,
Sumit
