### ISSUE TITLE
NMNIST

### ISSUE THREAD

**Issue by XDUSPONGE** [bamsumit/slayerPytorch#51]
Hello, thanks for your wonderful job. 
For the full NMNIST dataset, I did not find the train.txt and the test.txt, so could you offer it to me if it is convenient to you.
Thanks veray much

**Comment by chenjiefighting** [comment]
First of all, you should select  \exampleLoihi\02_NMNIST, then you see NMNISTsamll.zip, it is in the file.

**Comment by cglagovich** [comment]
If you follow the format provided in the small NMNIST train.txt and test.txt you could create the full NMNIST equivalents. I can provide code for that if you need.

**Comment by kingkong135** [comment]
@cglagovich you can provide code for me ? Thanks you very much.
