### ISSUE TITLE
occurs error when run DVS-Gesture

### ISSUE THREAD

**Issue by chenjiefighting** [bamsumit/slayerPytorch#54]
I've done the pre-processing and generated the file, and when I run ibmGestureTrain.py the following error occurs:

(chenjie) chenjie@arthur-PR4904P:/mnt/big_disk/2020/chenjie/slayerPytorch-master/exampleLoihi/03_IBMGesture$ python ibmGestureTrain.py
Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
Traceback (most recent call last):
  File "ibmGestureTrain.py", line 165, in <module>
    input, target, label = trainingSet[i]
  File "ibmGestureTrain.py", line 25, in __getitem__
    inputSpikes = snn.io.read2Dspikes(
  File "/home/chenjie/.conda/envs/chenjie/lib/python3.8/site-packages/slayerSNN-0.0.0-py3.8.egg/slayerSNN/spikeFileIO.py", line 258, in read2Dspikes
    tEvent =( (inputAsInt[2::5] << 16) | (inputAsInt[3::5] << 8) | (inputAsInt[4::5]) ) & 0x7FFFFF
ValueError: operands could not be broadcast together with shapes (49861306,) (49861305,)

**Comment by kingkong135** [comment]
@chenjiefighting I got the same error, how can you fix it ?

**Comment by chenjiefighting** [comment]
I am sorry to tell you that I can't fix it until now, but I print the inputAsInt.shape, I found inputAsInt[2 : : 5].shape is different from inputAsInt[3 : : 5].shape and inputAsInt[4 : : 5].shape, actually, they should be same. 



![116769284463652215](https://user-images.githubusercontent.com/76989858/113376201-be80da80-93a3-11eb-9877-4152345d61f7.png)

**Comment by bamsumit** [comment]
Not sure what preprocessing you have done. This might help: https://github.com/bamsumit/slayerPytorch/issues/37#issuecomment-680762632

Also you can get the full dvsGesture dataset converted to numpy here:
Train: https://www.neuromorphic-vision.com/public/downloads/ibmGestureTrain.tar.gz
Test : https://www.neuromorphic-vision.com/public/downloads/ibmGestureTest.tar.gz

**Comment by kingkong135** [comment]
@bamsumit  Thanks for your dataset, i downloaded, unzip it, but still run the error.

After a while of tracing, the read2Dspikes () function in the spikeFileIO.Py file I saw an error reading the .npy file. 
@chenjiefighting You can edit in that function (note using only .npy file) like so:

![Screenshot from 2021-04-02 16-03-18](https://user-images.githubusercontent.com/37267652/113401062-023c0a00-93cd-11eb-910e-94fee513e798.png)

![Screenshot from 2021-04-02 16-05-46](https://user-images.githubusercontent.com/37267652/113401294-5cd56600-93cd-11eb-9e4d-6f69efab5d13.png)



I have tried and it seems to work.  Thanks a lot for the help.

**Comment by bamsumit** [comment]
There is a utility in `spikeFileIO` to directly read from numpy events. So you just needed to replace `read2Dspikes` with `readNpSpikes`.

**Comment by chenjiefighting** [comment]
@kingkong135 Thanks a lot for your reply. But it occurued another problem. My .npy files and train.txt are as follow:
![1](https://user-images.githubusercontent.com/76989858/113504072-516a7200-9568-11eb-9a37-836378858df7.PNG)
![2](https://user-images.githubusercontent.com/76989858/113504077-54fdf900-9568-11eb-9854-eb6569db8fd7.PNG)
![3](https://user-images.githubusercontent.com/76989858/113504082-57f8e980-9568-11eb-9cbe-179641333121.PNG)
I am not sure if I processed the data incorrectly. Can you tell me how to deal with the data at your convenience. Thanks a lot.

**Comment by kingkong135** [comment]
I load the data set above https://github.com/bamsumit/slayerPytorch/issues/54#issuecomment-812314698 then I create train.txt and test.txt like: 
[test.txt](https://github.com/bamsumit/slayerPytorch/files/6257275/test.txt)
[train.txt](https://github.com/bamsumit/slayerPytorch/files/6257276/train.txt)

All above file in foder data/
Config in file network.yaml like: 

>  path:
        in:      data/
        train:   data/train.txt
        test:    data/test.txt

And code in # Define dataset module:

class IBMGestureDataset(Dataset):
    def __init__(self, datasetPath, sampleFile, samplingTime, sampleLength):
        self.path = datasetPath
        self.samples = pd.read_csv(sampleFile)
        self.samplingTime = samplingTime
        self.nTimeBins = int(sampleLength / samplingTime)

    def __getitem__(self, index):
        # Read inoput and label
        inputIndex = self.samples['sample'][index]
        classLabel = self.samples['labels'][index]
        # Read input spike
        inputSpikes = snn.io.readNpSpikes(
            self.path + str(inputIndex) + '.npy'
        ).toSpikeTensor(torch.zeros((2, 128, 128, self.nTimeBins)),
                        samplingTime=self.samplingTime)
        # Create one-hot encoded desired matrix
        desiredClass = torch.zeros((11, 1, 1, 1))
        desiredClass[classLabel, ...] = 1

        return inputSpikes, desiredClass, classLabel

    def __len__(self):
        return self.samples.shape[0]


Hope can help you.

**Comment by chenjiefighting** [comment]
Thank you. I think there were errors in changing names of .npy files. Anyway, thanks a lot. @kingkong135

**Comment by chenjiefighting** [comment]
Thank you. I think there were errors in changing names of .npy files. Anyway, thanks a lot. @kingkong135

**Comment by chenjiefighting** [comment]
> I load the data set above #54 (comment) then I create train.txt and test.txt like:
> test.txt
> train.txt
I want to ask how train.txt and test.txt are generated？
