### ISSUE TITLE
How to augmented spikes in slayer ? 

### ISSUE THREAD

**Issue by kingkong135** [bamsumit/slayerPytorch#59]
I have a question is can augment spikes as augment image? If have, know how to code in the slayer?
And let me ask more, how to calculate Theta, tauSr and tauRef in SLAYER Loihi module ? 

Thanks in advance.

**Comment by bamsumit** [comment]
It is recommended to augment the spike events like rotation, shift, skew etc. You can write your own for simple ones. For more augmentation options, have a look at this [repository](https://github.com/neuromorphs/tonic).

There is not tauSr, tauRef for Loihi. There are Loihi specific parameters like vThMant, vDecay, iDecay. See one of the Loihi examples.
