### ISSUE TITLE
Auto Loihi - how to load generated model on Loihi hardware

### ISSUE THREAD

**Issue by cglagovich** [bamsumit/slayerPytorch#61]
I see in the auto/loihi.py file, the idea is that after we train an auto model we can generate the hdf5 file and directly load that into nxsdk. Is there a tutorial or instructions on how to do that? As of now it seems as though I will have to follow d_slayer_gestures_notebook.ipynb from nxsdk-apps and manually create each layer and quantize the weights myself. Is there an automatic way to to do this?

Thanks!

**Comment by bamsumit** [comment]
Hi, please redirect this question to INRC confluence page. Short answer is yes, there is an automatic way to do it.
