### ISSUE TITLE
python -m unittest Error：ERROR: test_slayer012 (unittest.loader._FailedTest)

### ISSUE THREAD

**Issue by GitHubmalajava** [bamsumit/slayerPytorch#64]
I used anaconda environment with py36 and torch1.9,It has error:
ImportError: Failed to import test module: test_slayer012
Traceback (most recent call last):
  File "D:\Anaconda3\envs\VTS\lib\unittest\loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "D:\Anaconda3\envs\VTS\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "F:\VT_SNN-master\slayerPytorch\test\test_slayer012.py", line 41, in <module>
    pspGT = slayer.psp(spikeIn)
  File "D:\Anaconda3\envs\VTS\lib\site-packages\slayersnn-0.0.0-py3.6.egg\slayerSNN\slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "D:\Anaconda3\envs\VTS\lib\site-packages\slayersnn-0.0.0-py3.6.egg\slayerSNN\slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

**Comment by bamsumit** [comment]
Hi @GitHubmalajava,

I think `spikeIn.dtype` is `torch.double` instead of `torch.float`. Can you help me verify that? If it is the case, try changing line 35 to
`spikeIn = torch.zeros((N, C, H, W, Ns), dtype=torch.float).to(device)`
and see if it works.

**Comment by GitHubmalajava** [comment]
@bamsumit ，
OK，I will try it again,but Recently my program encountered a new error while testing，This is an error I encountered while downloading and debugging directly from this GitHub. The previous error was in the paper ‘Event-Driven Visual-Tactile Sensing
And Learning for Robots ’ in the author's Github address to download the Slayer error.Error:
Traceback (most recent call last):
  File "D:\Slayer\slayerPytorch-master\test\test_slayer003.py", line 99, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

**Comment by GitHubmalajava** [comment]
@bamsumit ,
In the VT_SNN project I downloaded from GitHub, that is, the address in the paper "Event-Driven Visual-Tactile Sensingand Learning for Robots", after you modified the code through your method, the program still shows the previous error. This error occurs in both float and double.
And thank you for your help

**Comment by bamsumit** [comment]
There is definitely error in your installation. Run this and send me the output and plots.

`python -m unittest test_slayer003.py --verbose`

**Comment by GitHubmalajava** [comment]
@bamsumit ，
I installed the Slayer package in my new Conda environment，I see that previous readers seem to have encountered the same problem as me. Perhaps the test can only be run once, maybe multiple tests make the PyCharm environment unclean?
I ran the command:python -m unittest test_slayer003.py --verbose，but it show the error:
(Slayer) F:\slayerPytorch-master\test>python -m unittest test_slayer003.py --verbose
loss : tensor(10.9903, grad_fn=<CopyBackwards>)
Layer2 gradient error : 0.00017182110937410657
Layer1 gradient error : 9.425988302811799e-07
test (test_slayer003.testGradients) ... FAIL

======================================================================
FAIL: test (test_slayer003.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\slayerPytorch-master\test\test_slayer003.py", line 100, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)

**Comment by bamsumit** [comment]
There should not be any problem when you run the tests multiple times. I don't see any reason for that.

If you have your display environment set correctly, it should also show some plots. That will be useful to see what is going on.

Do other unittests pass?

**Comment by GitHubmalajava** [comment]
@bamsumit ，
yes, all the other unnitest were successful, except test_slayer003, that means there should be no problem with my environment, and I don't know what the problem is ，I will continue to try other solutions

**Comment by bamsumit** [comment]
show me your plots.

**Comment by bamsumit** [comment]
Or do this if you are not getting the plot

run `python -i test_slayer003.py`
and evaluate the following
```
>>> gradW2
>>> snn.fc2.weight.grad.reshape((Nout, Nhid)).cpu().numpy()
>>> gradW2 - snn.fc2.weight.grad.reshape((Nout, Nhid)).cpu().numpy()
```

**Comment by GitHubmalajava** [comment]
No plot, when I use --verbose, there are only print statements. And the following description
(Slayer) F:\slayerPytorch-master\test>python -m unittest test_slayer003.py --verbose
loss : tensor(10.9903, grad_fn=<CopyBackwards>)
Layer2 gradient error : 0.00017182110937410657
Layer1 gradient error : 9.425988302811799e-07
test (test_slayer003.testGradients) ... FAIL

======================================================================
FAIL: test (test_slayer003.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\slayerPytorch-master\test\test_slayer003.py", line 100, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

----------------------------------------------------------------------
Ran 1 test in 0.000s

**Comment by GitHubmalajava** [comment]
@bamsumit ，
I run python -i test_slayer003.py,show this:
(Slayer) F:\slayerPytorch-master\test>python -i test_slayer003.py
F
======================================================================
FAIL: test (__main__.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_slayer003.py", line 100, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
Traceback (most recent call last):
  File "test_slayer003.py", line 128, in <module>
    unittest.main()
  File "D:\Anaconda3\envs\Slayer\lib\unittest\main.py", line 101, in __init__
    self.runTests()
  File "D:\Anaconda3\envs\Slayer\lib\unittest\main.py", line 273, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: True
----------------------------------------------------------------
I printed out all the parameters you required, but the result is still greater than 1e-4

**Comment by bamsumit** [comment]
Please post the outputs

**Comment by GitHubmalajava** [comment]
@bamsumit ，
gradW2: [1.9745  1.2898  4.3738  0.24559 3.0589  1.8519  0.40308 2.1371  4.0384
 0.83227 1.1828  2.5494  3.2402  2.064   3.7114  3.6431  1.2011  1.5707
 5.1058  1.552   0.22971 5.9916  1.4358  0.87923 0.53278]

snn.fc2.weight.grad.reshape((Nout, Nhid)).cpu().numpy(): 
[[1.973393   1.2891388  4.3724446  0.24551392 3.0578804  1.8514252
  0.40299684 2.1365738  4.037206   0.83165765 1.1824799  2.5485234
  3.2391357  2.063465   3.710301   3.6416183  1.2006819  1.5701736
  5.1040173  1.5515006  0.22964478 5.9902925  1.4353371  0.8790207
  0.5325508 ]]

 gradW2 - snn.fc2.weight.grad.reshape((Nout, Nhid)).cpu().numpy(): 
[[1.10703659e-03 6.61206055e-04 1.35537033e-03 7.60839844e-05
  1.01959839e-03 4.74829102e-04 8.31619072e-05 5.26208496e-04
  1.19382706e-03 6.12351913e-04 3.20141602e-04 8.76573944e-04
  1.06425781e-03 5.34881592e-04 1.09907761e-03 1.48174820e-03
  4.18075180e-04 5.26378822e-04 1.78274231e-03 4.99441147e-04
  6.52246094e-05 1.30745087e-03 4.62933350e-04 2.09309082e-04
  2.29188232e-04]]

**Comment by bamsumit** [comment]
The gradients look more or less close to the ground truth. Just try one of the example training and see if it learns. If it works, you are probably good to continue training.

**Comment by GitHubmalajava** [comment]
@bamsumit ，
OK, it can get back to work. And Thank you very much for your help. Look forward to the Slayer update. Thanks again
