### ISSUE TITLE
What is the contribution of "slayer.delayShift" to the SNN model?

### ISSUE THREAD

**Issue by forestfangsenlin** [bamsumit/slayerPytorch#66]
Hello, I want to ask what is the contribution of "slayer.delayShift" to the SNN model, I mean, there does not seem to be much difference in accuracy when adding or without adding the slayer.delayShift function to the model. Does the slayer.delayShift function act as the nonlinear function like Sigmod function in CNN model?

**Comment by bamsumit** [comment]
The `delayShift` simulates 1 time steps taken for a spike to travel from source neuron's output axon to destination synapse in a real hardware. It is there for hardware consistency in __Loihi__ (__note__: it is not used in SRM model). Typically it does not affect the accuracy whatsoever unless your simulation timesteps is comparable to the number of layers you have.

For e.g. if your network has 7 layers and you are running the network for just 8 time steps, then your output for the first 7 time steps would be zero as it would take 7 time steps for the input to propagate through all the layers.

**Comment by forestfangsenlin** [comment]
Thank you for your serious explanation. By the way, if there is some function in Slayer act as the nonlinear function like Sigmod function in CNN model? I recently read a paper, it uses temporal coding to achieve the effect of the nonlinear function.

**Comment by bamsumit** [comment]
The non-linear function is the spike response and reset non-linearity in the neuron dynamics. I am not sure what exactly you are getting at, but you can use torch any torch activation you desire if you want.
