### ISSUE TITLE
Plot spikes in hidden layers

### ISSUE THREAD

**Issue by zenmar** [bamsumit/slayerPytorch#67]
Is it possible to plot the spike-traffic happening inside the SNN in SLAYER / SLAYERLoihi for analysis ?
How could I access it?

Another question regarding snnAuto; is there some documentation on how to use it ? I saw the example with an MLP, but I'm unsure how to i.e. define a spiking-conv layer.

Thanks

**Comment by zenmar** [comment]
Also, is it possible to plot/visualize the neuron's state (i.e. membrane potential) over timesteps?

**Comment by bamsumit** [comment]
For slayerAuto, just follow the layer definition convention defined here: https://bamsumit.github.io/slayerPytorch/build/html/slayerParams.html

You can save the spike in each intermediate layer or assign it to a variable and visualize it as you wish.

For membrane voltage, you can store the voltage variable as follows.
```
voltage = slayer.psp(self.fc(input))
spike = slayer.spike(voltage)
```
The refractory response will be applied internally when `slayer.spike` is called and will be reflected in `voltage`.
