### ISSUE TITLE
Are there any examples of non-spiking datasets?

### ISSUE THREAD

**Issue by jimzhou112** [bamsumit/slayerPytorch#68]
Hello,

I'm looking to use SLAYER for a non-spiking dataset similar to MNIST. Are there any examples of SLAYER being applied to non-spiking input datasets? I noticed that in the NIPS paper there were accuracy comparisons done on MNIST, but no corresponding example code in the codebase.

If there aren't any examples, how do I modify the examples done on spiking datasets to take in non-spiking datasets? The paper states that MNIST images were converted into spike trains spanning 25 ms using Generalized Integrate and Fire Model of neuron. What is the syntax for that in code?

Thanks for the help

**Comment by bamsumit** [comment]
There are any examples available for non-spiking datasets. 

You will have to write your own spike conversion process and then the training for MNIST is going to be similar to NMNIST. There are a couple of functions that will help you implement GLM spike encoding method:

```
psp_layer = slayer.pspLayer()
encoded_spike = slayer.spike(psp_layer(slayer.replicateInTime(input_image))) # input image in NCHW format
``` 

You can also use a filter bank to encode. Just replace `slayer.pspLayer()` with `slayer.pspFilter(nFilter=8, filterlength=16)` (_I realized the arguments for pspFitler in the documentation are wrong!_)

__Note:__ Similar code works. I have not verified the above code snippet.
