### ISSUE TITLE
Functionality similar to ConvLSTM or ConvGRU

### ISSUE THREAD

**Issue by ChidanandKumarKS** [bamsumit/slayerPytorch#85]
@bamsumit 
Do we have any components of spiky networks for ConvLSTM and ConvGRU? Kindly reply

**Comment by bamsumit** [comment]
There is no spiking equivalent of LSTM or GRU. The recurrent alternatives for SNNs are [LSNN](https://proceedings.neurips.cc/paper/2018/file/c203d8a151612acf12457e4d67635a95-Paper.pdf) and [LMU](https://papers.nips.cc/paper/2019/file/952285b9b7e7a1be5aa7849f32ffff05-Paper.pdf).
