### ISSUE TITLE
run ‘python setup.py install‘ on windows, errors occured

### ISSUE THREAD

**Issue by XiaoxinWang98** [bamsumit/slayerPytorch#86]
![1](https://user-images.githubusercontent.com/87742190/156748009-f5240d36-8b39-4cca-8a89-6fd90bd74cb3.png)
I try to run Slayerpython on windows. But it failed.
How can i solve the problem below?
thanks.

**Comment by XiaoxinWang98** [comment]
This is due to the CUDA version. The problem has now been resolved.
Reference: https://github.com/facebookresearch/pytorch3d/issues/1024#issuecomment-1007360385

**Comment by MintonLee** [comment]
老哥，所以最终是怎么解决的？
