### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by never-to-never** [bamsumit/slayerPytorch#99]
I executed the command 'python setup.py install' successfully
![image](https://user-images.githubusercontent.com/27321035/220799476-b4f969fd-f04b-4e90-8848-6c1f9ac28b1d.png)
However, an error is reported when testing the installation with 'python -m unittest'. What is the problem? Screenshot below:
![image](https://user-images.githubusercontent.com/27321035/220799585-17904f55-5fb1-4800-991c-b4480fac7f1d.png)

**Comment by pbonazzi** [comment]
How did you solve this ?

**Comment by kkkkkkip** [comment]
Hello, have you solved the test problem

**Comment by sleipnier** [comment]
Could please inform us how did you slove the unittest problem? Thank you very much
